import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'images.unsplash.com' },
      { protocol: 'https', hostname: '**.supabase.co' },
      { protocol: 'https', hostname: '**.supabase.in' },
      // Retailer/brand sites the grocery product image library sources photos
      // from. These are third-party hosts we don't control — an image can go
      // missing or move if the source site changes, and hotlink protection on
      // a given host can still block the fetch even once it's trusted here.
      { protocol: 'https', hostname: '3d.walmartimages.com' },
      { protocol: 'https', hostname: '5.imimg.com' },
      { protocol: 'https', hostname: 'allibhavan.com' },
      { protocol: 'https', hostname: 'arabianorganics.com' },
      { protocol: 'https', hostname: 'assets.amul.com' },
      { protocol: 'https', hostname: 'assets.unileversolutions.com' },
      { protocol: 'https', hostname: 'assets.woolworths.com.au' },
      { protocol: 'https', hostname: 'b4023487.assetcdn.net' },
      { protocol: 'https', hostname: 'britannia-international.com' },
      { protocol: 'https', hostname: 'cdn-bjpdk.nitrocdn.com' },
      { protocol: 'https', hostname: 'cdn-media.nxtby.com' },
      { protocol: 'https', hostname: 'cdn.netmeds.tech' },
      { protocol: 'https', hostname: 'cdn01.pharmeasy.in' },
      { protocol: 'https', hostname: 'cdn1.jiomartjcp.com' },
      { protocol: 'https', hostname: 'cdn2.shopclues.com' },
      { protocol: 'https', hostname: 'content.jdmagicbox.com' },
      { protocol: 'https', hostname: 'creativewithmedia.com' },
      { protocol: 'https', hostname: 'darbaarmart.com' },
      { protocol: 'https', hostname: 'digitalcontent.api.tesco.com' },
      { protocol: 'https', hostname: 'dukaan.b-cdn.net' },
      { protocol: 'https', hostname: 'elfinic.com' },
      { protocol: 'https', hostname: 'evanaa.com' },
      { protocol: 'https', hostname: 'ewshopping.com' },
      { protocol: 'https', hostname: 'godrejyummiez.in' },
      { protocol: 'https', hostname: 'grainbro.com' },
      { protocol: 'https', hostname: 'greensshopping.com' },
      { protocol: 'https', hostname: 'himalayawellness.ae' },
      { protocol: 'https', hostname: 'himalayawellness.in' },
      { protocol: 'https', hostname: 'i0.wp.com' },
      { protocol: 'https', hostname: 'i5.walmartimages.com' },
      { protocol: 'https', hostname: 'ifmal.b-cdn.net' },
      { protocol: 'https', hostname: 'images-na.ssl-images-amazon.com' },
      { protocol: 'https', hostname: 'images.apollo247.in' },
      { protocol: 'https', hostname: 'img.clevup.in' },
      { protocol: 'https', hostname: 'img.magnific.com' },
      { protocol: 'https', hostname: 'indianbigbazzar.com' },
      { protocol: 'https', hostname: 'kbnaturals.in' },
      { protocol: 'https', hostname: 'kitchin.in' },
      { protocol: 'https', hostname: 'kmf-website.s3.ap-south-1.amazonaws.com' },
      { protocol: 'https', hostname: 'm.media-amazon.com' },
      { protocol: 'https', hostname: 'mamaearth.in' },
      { protocol: 'https', hostname: 'meatmasters.co.in' },
      { protocol: 'https', hostname: 'milletsforhealth.com' },
      { protocol: 'https', hostname: 'morrowfresh.com' },
      { protocol: 'https', hostname: 'myhitechstore.com' },
      { protocol: 'https', hostname: 'mysoresandalsoap.com' },
      { protocol: 'https', hostname: 'mysunpure.in' },
      { protocol: 'https', hostname: 'natures-secrets.co.za' },
      { protocol: 'https', hostname: 'naturevit.in' },
      { protocol: 'https', hostname: 'nellara.com' },
      { protocol: 'https', hostname: 'nutravantagestore.com' },
      { protocol: 'https', hostname: 'nyspiceshop.com' },
      { protocol: 'https', hostname: 'productimages.motatos.com' },
      { protocol: 'https', hostname: 'pronatureorganic.com' },
      { protocol: 'https', hostname: 'pxmshare.colgatepalmolive.com' },
      { protocol: 'https', hostname: 'richs.com' },
      { protocol: 'https', hostname: 'rukminim2.flixcart.com' },
      { protocol: 'https', hostname: 'samrudhionline.in' },
      { protocol: 'https', hostname: 'services.kpnfresh.com' },
      { protocol: 'https', hostname: 'shop.colgate.com' },
      { protocol: 'https', hostname: 'shop.dabur.co.uk' },
      { protocol: 'https', hostname: 'shop.gajanand.com' },
      { protocol: 'https', hostname: 'shop.ledelas.fr' },
      { protocol: 'https', hostname: 'shop.natcofoods.com' },
      { protocol: 'https', hostname: 'shoplineimg.com' },
      { protocol: 'https', hostname: 'shopwholly.com' },
      { protocol: 'https', hostname: 'southernsupermarket.com' },
      { protocol: 'https', hostname: 'static.freshtohome.com' },
      { protocol: 'https', hostname: 'static.wixstatic.com' },
      { protocol: 'https', hostname: 'sugunarotis.com' },
      { protocol: 'https', hostname: 'tathastubasket.com' },
      { protocol: 'https', hostname: 'tejashfoods.com' },
      { protocol: 'https', hostname: 'thespicepeople.in' },
      { protocol: 'https', hostname: 'true-elements.com' },
      { protocol: 'https', hostname: 'umedmart.com' },
      { protocol: 'https', hostname: 'wholesaler.pk' },
      { protocol: 'https', hostname: 'wonderlandfoods.in' },
      { protocol: 'https', hostname: 'www.ahabazaar.co.uk' },
      { protocol: 'https', hostname: 'www.bbassets.com' },
      { protocol: 'https', hostname: 'www.bizzotto.com' },
      { protocol: 'https', hostname: 'www.budgetmart.co.uk' },
      { protocol: 'https', hostname: 'www.chsugar.com' },
      { protocol: 'https', hostname: 'www.coconol.com.au' },
      { protocol: 'https', hostname: 'www.daburshop.com' },
      { protocol: 'https', hostname: 'www.dove-india.com' },
      { protocol: 'https', hostname: 'www.freedomhealthyoil.com' },
      { protocol: 'https', hostname: 'www.greenposhan.com' },
      { protocol: 'https', hostname: 'www.grodoor.in' },
      { protocol: 'https', hostname: 'www.happyandhealthy.co.nz' },
      { protocol: 'https', hostname: 'www.house-foods.com' },
      { protocol: 'https', hostname: 'www.indiagatefoods.com' },
      { protocol: 'https', hostname: 'www.instacart.com' },
      { protocol: 'https', hostname: 'www.keralaspicesonline.com' },
      { protocol: 'https', hostname: 'www.kpcashews.com' },
      { protocol: 'https', hostname: 'www.liliumcosmetic.com' },
      { protocol: 'https', hostname: 'www.mandalaorganics.in' },
      { protocol: 'https', hostname: 'www.mystore.in' },
      { protocol: 'https', hostname: 'www.patanjaliayurved.net' },
      { protocol: 'https', hostname: 'www.picknsave.co.uk' },
      { protocol: 'https', hostname: 'www.silkrute.com' },
      { protocol: 'https', hostname: 'www.topintownstore.com' },
      { protocol: 'https', hostname: 'www.treatsfromoz.com' },
      { protocol: 'https', hostname: 'www.tueminhgarden.vn' },
      { protocol: 'https', hostname: 'www.vhv.rs' },
    ],
  },
};

export default nextConfig;
